### ISSUE TITLE
Gochain can't connect to peer if i start with config.toml file

### ISSUE THREAD

**Issue by KursLabIgor** [gochain-io/gochain#330]
Initialising GoChain protocol            versions="[63 62]" network=60
i see in log such id of network, what does it mean? how to identify what is mainnet/test net

**Comment by KursLabIgor** [comment]
Reopen problem still reproduce
/gochain --rpc --ws --wsorigins * --syncmode full --config ./config.toml
As result gochain cant connect to peers

**Comment by jmank88** [comment]
Network and Chain ID for mainnet is `60`. For testnet it is `31337`.

How long did you let it run?
What does your `config.toml` look like? I wouldn't normally recommend  using `dumpconfig` since it tends to write a bunch of default parameters that don't add any value. Additionally, `HTTPTracing = true` doesn't do anything useful. The flag `--tracing.stackdriver` must be used instead.

**Comment by KursLabIgor** [comment]
after wait ~5-7 min gochain started. closed
